# Generated by Django 5.1.3 on 2024-11-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_task_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='postcode',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('line3', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('organisation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_address', to='accounts.organisation')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='accounts.addressconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='AddressFieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.addressconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
