# Generated by Django 5.1.3 on 2024-11-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_task_points'),
        ('accounts', '0006_auto_20241109_0121'),
    ]

    operations = [
    ]
