# Generated by Django 5.1.3 on 2024-11-09 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0005_task_points_0006_auto_20241109_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingoutlet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishingoutlet',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
