# Generated by Django 5.1.3 on 2024-11-09 15:11

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_publishingoutlet_created_publishingoutlet_modified'),
    ]

    operations = [
        # Removed RemoveField operation since 'configuration' is already removed
        
        # Removed AlterField for 'address_type' because it already exists
        
        # Keep the AlterField operation for 'organisation'
        migrations.AlterField(
            model_name='address',
            name='organisation',
            field=models.ForeignKey(
                default=1,  # Ensure that default=1 is appropriate. If not, adjust accordingly.
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresses',
                to='accounts.organisation'
            ),
            preserve_default=False,
        ),
    ]